// data/data.js
const websites = [
  {
    slug: 'clapier-lapin-interieur',
    name: 'Clapier Lapin Intérieur',
    category: 'https://clapier-lapin.pro/clapier-lapin-interieur',
    author: 'Hervé Liret',
    author_bio: 'Je suis Hervé Liret, passionné de lapins depuis mon enfance. J\'ai consacré ma vie à l\'étude et à l\'amélioration des habitats pour lapins. J\'aime partager mes connaissances à travers des articles et des guides pratiques. Mon objectif est de créer des environnements sûrs et confortables pour nos amis à longues oreilles.',
    author_img: './public/images/herve-liret.png',
  },
  {
    slug: 'clapier-lapin-exterieur',
    name: 'Clapier Lapin Extérieur',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/clapier-lapin-interieur',
    author: 'Patricia Rolland',
    author_bio: 'Je m\'appelle Patricia Rolland et je suis experte en soins des lapins et en conception de clapiers. J\'ai écrit plusieurs livres sur le sujet et je donne régulièrement des conférences. Je suis également une fervente défenseure du bien-être animal. Mon travail est guidé par la passion et le respect des animaux.',
    author_img: './public/images/patricia-rolland.png',
  },
  {
    slug: 'clapier-lapin-en-bois',
    name: 'Clapier Lapin en bois',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/clapier-en-bois',
    author: 'Alexandra Georges',
    author_bio: 'Je suis Alexandra Georges, architecte spécialisée dans les structures en bois. J\'ai une passion pour les animaux et je combine mes compétences pour créer des habitats confortables pour les lapins. J\'aime partager mes projets et idées innovantes. Mon but est de concevoir des espaces qui allient esthétique et fonctionnalité.',
    author_img: './public/images/alexandra-georges.png',
  },
  {
    slug: 'cage-lapin-interieur',
    name: 'Cage Lapin Intérieur',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/cage-interieur',
    author: 'Rodrigue Gauthier',
    author_bio: 'Je suis Rodrigue Gauthier, vétérinaire spécialisé dans les petits animaux. J\'ai une vaste expérience dans le soin des lapins et la conception de leurs habitats. Je suis également un auteur publié et un conférencier respecté. Mon engagement est de promouvoir la santé et le bien-être des lapins à travers mes connaissances et mon expertise.',
    author_img: './public/images/rodrigue-gauthier.png',
  },
  {
    slug: 'cage-lapin-exterieur',
    name: 'Cage Lapin Extérieur',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/cage-exterieur',
    author: 'Paul Rodiette',
    author_bio: 'Je suis Paul Rodiette, éleveur de lapins avec plus de 20 ans d\'expérience. Je suis connu pour mes méthodes innovantes et respectueuses des animaux. Je partage mes connaissances à travers des ateliers et des publications en ligne. Mon objectif est de garantir le bien-être des lapins tout en facilitant leur élevage.',
    author_img: './public/images/paul-rodiette.png',
  },
  {
    slug: 'cage-de-transport-lapin',
    name: 'Cage de Transport Lapin',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/cage-de-transport',
    author: 'Faniry Rutroire',
    author_bio: 'Je suis Faniry Rutroire, designer spécialisée dans les accessoires pour animaux. J\'ai développé plusieurs produits innovants pour le transport des lapins. Je suis également une blogueuse active, partageant des conseils et des astuces pour les propriétaires de lapins. Mon travail vise à rendre les déplacements des lapins aussi confortables et sûrs que possible.',
    author_img: './public/images/faniry-rutroire.png',
  },
  {
    slug: 'cage-lapin-xxl',
    name: 'Cage Lapin XXL',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/cage-xxl',
    author: 'Stanislas Leclercq',
    author_bio: 'Je suis Stanislas Leclercq, ingénieur en construction avec une passion pour les animaux. J\'ai conçu plusieurs modèles de cages XXL pour offrir plus d\'espace et de confort aux lapins. J\'aime partager mes connaissances techniques avec la communauté. Mon ambition est de créer des habitats qui répondent aux besoins spécifiques des lapins tout en étant pratiques pour leurs propriétaires.',
    author_img: './public/images/stanislas-leclercq.png',
  },
  {
    slug: 'enclos-interieur-lapin',
    name: 'Enclos Intérieur Lapin',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/enclos-interieur',
    author: 'Rodrigue Gauthier',
    author_bio: 'Je suis Rodrigue Gauthier, vétérinaire spécialisé dans les petits animaux. J\'ai une vaste expérience dans le soin des lapins et la conception de leurs habitats. Je suis également un auteur publié et un conférencier respecté. Mon engagement est de promouvoir la santé et le bien-être des lapins à travers mes connaissances et mon expertise.',
    author_img: './public/images/rodrigue-gauthier.png',
  },
  {
    slug: 'enclos-exterieur-lapin',
    name: 'Enclos Extérieur Lapin',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/enclos-exterieur',
    author: 'André-Pierre Roux',
    author_bio: 'Je suis André-Pierre Roux, paysagiste passionné par les animaux. Je conçois des enclos extérieurs qui s\'intègrent harmonieusement dans les jardins. Je suis également un consultant en aménagement paysager pour les propriétaires de lapins. Mon travail vise à créer des espaces extérieurs sécurisés et esthétiques pour les lapins.',
    author_img: './public/images/andre-pierre-roux.png',
  },
  {
    slug: 'enclos-modulable-lapin',
    name: 'Enclos Modulable Lapin',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/enclos-modulable',
    author: 'Francis Lefevre',
    author_bio: 'Je suis Francis Lefevre, ingénieur en design industriel. J\'ai créé plusieurs enclos modulables pour offrir flexibilité et confort aux lapins. Je suis également un passionné de bricolage et je partage mes projets DIY avec la communauté. Mon objectif est de permettre aux propriétaires de lapins de personnaliser leurs enclos selon leurs besoins.',
    author_img: './public/images/francis-lefevre.png',
  },
  {
    slug: 'parc-lapin',
    name: 'Parc Lapin',
    target_home: 'https://clapier-lapin.pro/',
    target_category: 'https://clapier-lapin.pro/enclos-modulable',
    author: 'Paula Uberti',
    author_bio: 'Je suis Francis Lefevre, ingénieur en design industriel. J\'ai créé plusieurs enclos modulables pour offrir flexibilité et confort aux lapins. Je suis également un passionné de bricolage et je partage mes projets DIY avec la communauté. Mon objectif est de permettre aux propriétaires de lapins de personnaliser leurs enclos selon leurs besoins.',
    author_img: './public/images/paula-uberti.png',
  },
];

//export default websites;
module.exports = websites;